# NumPY

### Import library


### Not recommended way

In [ ]:
import numpy
numpy.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
from numpy import *
array([1, 2, 3, 4])

array([1, 2, 3, 4])

### Recommended way:

In [ ]:
import numpy as np
np.array([1, 2])

array([1, 2])

###Arrays

In [ ]:
a = np.array([1, 2, 3, 4])
type(a)

numpy.ndarray

In [ ]:
a.dtype

dtype('int64')

In [ ]:
f = np.array([1.2, 1.3, 1.4])
f.dtype

dtype('float64')

In [ ]:
b = np.array([1, 'abc', True])
b.dtype

dtype('<U21')

In [ ]:
b.dtype.type

numpy.str_

In [ ]:
a[0]

1

In [ ]:
a[0] = 10
a

array([10,  2,  3,  4])

In [ ]:
a[0] = 11.5
a

array([11,  2,  3,  4])

In [ ]:
a[0] = "string"

ValueError: invalid literal for int() with base 10: 'string'

In [ ]:
a.ndim

1

In [ ]:
a.shape

(4,)

In [ ]:
a.size

4

In [ ]:
a = np.array([[11, 12, 13], [21, 22, 23]])
a

array([[11, 12, 13],
       [21, 22, 23]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a[0,0]

11

In [ ]:
a[1,2]

23

####Array indexing

In [ ]:
#row
a[1,]

array([21, 22, 23])

In [ ]:
#row
a[1, :]

array([21, 22, 23])

In [ ]:
#column
a[:, 2]

array([13, 23])

In [ ]:
a[:, 0:2]

array([[11, 12],
       [21, 22]])

In [ ]:
a[0, 1:]

array([12, 13])

####Alternative options to create array

[documentation](https://numpy.org/doc/stable/reference/routines.array-creation.html)

In [ ]:
a = np.zeros((3, 5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
a = np.ones((2,3,4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
a.shape

(2, 3, 4)

In [ ]:
a.size

24

In [ ]:
a = np.full((2, 3), 7)
a

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.full_like(a, 11)

array([[11, 11, 11],
       [11, 11, 11]])

In [ ]:
a = np.arange(0, 10, 2)
a

array([0, 2, 4, 6, 8])

###Operations with arrays
### Universal functions (ufunc)

In [ ]:
a = np.ones((4))
a

array([1., 1., 1., 1.])

In [ ]:
b = np.full_like(a, 2)
b

array([2., 2., 2., 2.])

In [ ]:
np.add(a, b)

array([3., 3., 3., 3.])

In [ ]:
a + b

array([3., 3., 3., 3.])

In [ ]:
a - b

array([-1., -1., -1., -1.])

In [ ]:
a * b

array([2., 2., 2., 2.])

In [ ]:
a / b

array([0.5, 0.5, 0.5, 0.5])

In [ ]:
c = np.zeros((1,3))
np.cos(c)

array([[1., 1., 1.]])

### Vectorization

All previous operations are element-wise and were called without loops. This because all of them are vectorized operations.

In [ ]:
a_list = [i for i in range(100000)]
type(a_list)

list

In [ ]:
from datetime import datetime
start = datetime.now()
a2_list = [a + 2 for a in a_list]
end = datetime.now()
loop_time = (end-start).total_seconds()
print(loop_time)

0.012803


In [ ]:
%%timeit
a2_list = [a + 2 for a in a_list]

6.27 ms ± 170 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
a_arr = np.array(a_list)
type(a_arr)

numpy.ndarray

In [ ]:
start = datetime.now()
a2_arr = a_arr + 2
end = datetime.now()
vec_time = (end-start).total_seconds()
print(vec_time)

0.005663


In [ ]:
%%timeit
a2_arr = a_arr + 2

57.6 µs ± 3.25 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
loop_time/vec_time

2.2608158220024723

### Broadcasting

[Documentations](https://numpy.org/doc/stable/user/basics.broadcasting.html)

When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimensions and works its way left. Two dimensions are compatible when

* they are equal, or
* one of them is 1

In [ ]:
a = np.array([1, 1, 1])
a + 1

array([2, 2, 2])

In [ ]:
a = np.ones((3, 2))
a.shape

(3, 2)

In [ ]:
b = np.array([5, 5])
b.shape

(2,)

In [ ]:
b

array([5, 5])

In [ ]:
a+b

array([[6., 6.],
       [6., 6.],
       [6., 6.]])

In [ ]:
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
b = np.array([5, 5, 5])
a + b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [ ]:
b+a

ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [ ]:
c = np.ones((4,2))
d = np.full((2,1),3)
c+d

ValueError: operands could not be broadcast together with shapes (4,2) (2,1) 

In [ ]:
a1 = np.zeros((2,3,5))
a1

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
a2 = np.ones((2,3))
a2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a1 + a2

ValueError: operands could not be broadcast together with shapes (2,3,5) (2,3) 

### Arrays are mutable!!!

In [ ]:
a = np.array([1, 2, 3])
b = a
b

array([1, 2, 3])

In [ ]:
b[1] = 11
b

array([ 1, 11,  3])

In [ ]:
a

array([ 1, 11,  3])

In [ ]:
b = a.copy()
b[1] = 111
b

array([  1, 111,   3])

In [ ]:
a

array([ 1, 11,  3])

In [ ]:
a+=2
a

array([ 3, 13,  5])