# Linear Algebra
##Addition of vectors and matrices

Pure Python

In [ ]:
def add_lists(x, y):
  res = []
  for i in range(len(x)):
    res.append(x[i] + y[i])
  return res
a = [1, 2, 3]
b = [1, 1, 1]
add_lists(a, b)

[2, 3, 4]

In [ ]:
a + b

[1, 2, 3, 1, 1, 1]

Uning Numpy

In [ ]:
import numpy as np
a_vec = np.array(a)
b_vec = np.array(b)
a_plus_b = a_vec + b_vec
a_min_b = a_vec - b_vec
a_plus_b

array([2, 3, 4])

In [ ]:
a_min_b

array([0, 1, 2])

In [ ]:
#not recommended
a = np.matrix([
    [11, 12],
    [21, 22]
])
a

matrix([[11, 12],
        [21, 22]])

In [ ]:
a = np.array([
    [1, 2],
    [3, 4]
])
a

array([[1, 2],
       [3, 4]])

In [ ]:
b = np.array([
    [11, 12],
    [13, 14]
])
a + b

array([[12, 14],
       [16, 18]])

##Multiplication of vectors and matrices

In [ ]:
np.matmul(a, b)

array([[37, 40],
       [85, 92]])

In [ ]:
# matmul is matrix multiplication, but "*" is element-wise product
a * b

array([[11, 24],
       [39, 56]])

In [ ]:
#dot product or scalar product
np.dot(a, b)

array([[37, 40],
       [85, 92]])

In [ ]:
np.dot(np.array([1, 2]), np.array([2, 2]))

6

In [ ]:
np.dot(3, 4)

12

In [ ]:
np.matmul(2, 3)

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [ ]:
a = np.array([
    [1, 2],
    [3, 4]
])
b = np.ones((3,3))
a.shape

(2, 2)

In [ ]:
b.shape

(3, 3)

In [ ]:
np.matmul(a, b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

## Transposed matrix

In [ ]:
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [ ]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b.transpose()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Vector norm

In [ ]:
a = np.array([1, 2, 3])
np.linalg.norm(a)

3.7416573867739413

In [ ]:
a

array([1, 2, 3])

In [ ]:
import math
def vec_norm(x):
  res = math.sqrt(sum([el**2 for el in x]))
  return res
vec_norm(a)

3.7416573867739413

# Descriptive statistics

## Mean

In [ ]:
a_list = [1000, 2000, 2300, 2300, 2300, 3500, 3600, 10000]
a_mean = sum(a_list)/len(a_list)
a_mean

3375.0

In [ ]:
np.mean(a_list)

3375.0

In [ ]:
a_array = np.array(a_list)
a_array.mean()

3375.0

In [ ]:
a_list.mean()

AttributeError: 'list' object has no attribute 'mean'

In [ ]:
a = np.array([1000, 2000, 2300, 2300, 2300, 3500, 3600, 10000, np.nan])
a

array([ 1000.,  2000.,  2300.,  2300.,  2300.,  3500.,  3600., 10000.,
          nan])

In [ ]:
a.mean()

nan

In [ ]:
np.nanmean(a)

3375.0

In [ ]:
a_m = np.array([
    [1, 2],
    [3, 4]
])
a_m.mean()

2.5

## Mode

In [ ]:
import statistics
statistics.mode(a_list)

2300

In [ ]:
statistics.mode(a_array)

2300

In [ ]:
from scipy import stats
stats.mode(a_array)

ModeResult(mode=2300, count=3)

In [ ]:
#array because multimode is possible
stats.mode(a_array).mode

2300

## Median

In [ ]:
np.median(a_array)

2300.0

In [ ]:
statistics.median(a_array)

2300.0

## Standard deviation

Numpy.std ddof : int, optional Means Delta Degrees of Freedom. The divisor used in calculations is N - ddof, where N represents the number of elements. By default ddof is zero.

In [ ]:
np.std(a_array)

2620.9492555179318

In [ ]:
np.std(a_array, ddof = 1)

2801.912612076666

In [ ]:
statistics.stdev(a_array)

2801.9125610910846

In [ ]:
statistics.pstdev(a_array)

2620.9492555179318

## Percentiles

In [ ]:
np.percentile(a_array, 25)

2225.0

In [ ]:
np.percentile(a_array, 95)

7759.999999999996

In [ ]:
np.percentile(a_array, [25, 50, 75])

array([2225., 2300., 3525.])